export { CatfactForm } from './catfactForm'
export { useCatfactQuery } from './catfactForm'
export { AgifyForm } from './agifyForm'
export { schema } from './agifyForm'
export { useAgifyForm } from './agifyForm'
export { useAgifyQuery } from './agifyForm'